[global]
port = 8001
ical_url = "https://p65-caldav.icloud.com/published/2/MTE5ODI2NzE4NjcxMTk4MtLolaPZM4dfZ51A3OlBfYVUUXcQZjz78jFeosDa99weVVZ1VlGwX0uWdcKky5qOUGQwMqiSYbPKjh6M_6K-SlY"
travelynx_token = "2889-3e8a5f34-d1b0-4622-94e8-86efe054d498"